service: myserverlessproject3

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    region: eu-west-1
    stage: dev
    environment:
        tableName: ${self:custom.tableName}
        bucketName: ${self:custom.bucketName}
        signupTableName: ${self:custom.signupTableName}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - s3:*
              - ses:*
          Resource: '*'

plugins:
    - serverless-webpack
    - serverless-step-functions

package:
    individually: true

custom:
    tableName: player-points-table
    signupTableName: signup-table-name
    bucketName: myserverlessprojectuploadbucket-12312356

stepFunctions:
    validate: true
    stateMachines:
        reminderEmail:
            name: reminderEmail
            events:
                - http:
                      path: signup-with-reminders
                      method: POST
                      cors: true
            definition: ${file(./stepFunction.yml)}

functions:
    getPlayerScore:
        handler: lambdas/endpoints/getPlayerScore.handler
        events:
            - http:
                  path: get-player-score/{ID}
                  method: GET
                  cors: true
    createPlayerScore:
        handler: lambdas/endpoints/createPlayerScore.handler
        events:
            - http:
                  path: create-player-score/{ID}
                  method: POST
                  cors: true
    updatePlayerScore:
        handler: lambdas/endpoints/updatePlayerScore.handler
        events:
            - http:
                  path: update-player-score/{ID}
                  method: PUT
                  cors: true
    getGameScores:
        handler: lambdas/endpoints/getGameScores.handler
        events:
            - http:
                  path: get-game-scores/{game}
                  method: GET
                  cors: true

    getGamesForPlayer:
        handler: lambdas/endpoints/getGamesForPlayer.handler
        events:
            - http:
                  path: get-games-for-player/{playerID}
                  method: GET
                  cors: true

    sendEmail:
        handler: lambdas/endpoints/sendEmail.handler
        events:
            - http:
                  path: send-email
                  method: POST
                  cors: true

    addSignup:
        handler: lambdas/stepFunctionLambdas/addSignup.handler
    getSignup:
        handler: lambdas/stepFunctionLambdas/getSignup.handler
    sendReminderEmail:
        handler: lambdas/stepFunctionLambdas/sendReminderEmail.handler

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.bucketName}
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                    - AttributeName: game
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST

                GlobalSecondaryIndexes:
                    - IndexName: game-index
                      KeySchema:
                          - AttributeName: game
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

        MyEmailSignupTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.signupTableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
